name: delete test file and run security analysis

on:
  push:
    branches: [ main, master]

  pull_request:
     branches: [master]

jobs:
  delte-workflow:
    runs-on : ubuntu-latest
    steps:
      - name: Remove file 
        uses: JesseTG/rm@v1.0.3
        with:
          path: ${{ github.workspace }}/.github/workflows/test-workflow.yaml

