name: delete file and run security analysis

on:
  push:
    branches: [ main, master]

  pull_request:
     branches: [master]

jobs:
  delte-workflow:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Remove file 
        run: |
          if [ -f path/to/file.txt ]; then
            echo "Deleting file..."
            git rm -f path/to/file.txt
            git commit -m "Delete file.txt" -a
          else
            echo "File not found. Skipping deletion."
          fi

