name: delete file and run security analysis

on:
  push:
    branches: [ main, master]

  pull_request:
     branches: [master]

jobs:
  delte-workflow:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Remove file 
        run: |
          if [ -f .github/workflows/test-workflow.yaml ]; then
            echo "Deleting file..."
            git rm -f p.github/workflows/test-workflow.yaml
            git commit -m "Delete .github/workflows/test-workflow.yaml" -a
          else
            echo "File not found. Skipping deletion."
          fi

